add: エラーハンドリング

diff --git a/.github/workflows/cleanup-dev-branches.yml b/.github/workflows/cleanup-dev-branches.yml
--- a/.github/workflows/cleanup-dev-branches.yml
+++ b/.github/workflows/cleanup-dev-branches.yml
@@ -18,21 +18,28 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
+          set -e
+          function error_handler(){
+            echo "Deleting failed"
+          }
+
+          trap error_handler ERR
           BRANCHES=$(git branch -r | grep 'origin/dev-' | sed 's/origin\///')
 
           for branch in ${BRANCHES}; do
             FULL_BRANCH_NAME="refs/remotes/origin/${branch}"
             LAST_COMMIT_DATE=$(git log -1 --format="%ai" "${FULL_BRANCH_NAME}" | cut -d" " -f1)
             LAST_COMMIT_TS=$(date -d "${LAST_COMMIT_DATE}" +%s)
-            WEEK_AGO_TS=$(date -d '-1 minutes' +%s)
+            SEVEN_DAYS_AGO_TS=$(date -d '-7 days' +%s)
 
-            if [ ${LAST_COMMIT_TS} -lt ${WEEK_AGO_TS} ]; then
+            if [ ${LAST_COMMIT_TS} -lt ${SEVEN_DAYS_AGO_TS} ]; then
               echo "Deleting old branch: ${branch}"
               # For safety, keep 'dry-run' during testing. Remove it when ready for actual deletion.
               #git push --delete origin ${branch} --dry-run
               # To actually delete the branch, comment out the above line and uncomment the line below
               git push --delete origin ${branch}
+              echo "Old branch: ${branch} was successfully deleted."
             else
-              echo "Branch is not older than a week: ${branch}"
+              echo "Branch is not older than 7 days: ${branch}"
             fi
           done
